CREATE TABLE IF NOT EXISTS ITEMS (
    TCIN INTEGER NOT NULL UNIQUE,
    DPCI TEXT,
    DEPARTMENT_NO INTEGER,
    CLASS_NO INTEGER,
    ITEM_NO INTEGER,
    UPC TEXT,
    ITEM_NAME TEXT,
    PRICE DOUBLE,
    ON_HAND INTEGER,
    ON_SALE BOOLEAN,
    FLOOR_LOCATION TEXT
);